### PR TITLE
Mapper view tweaks + documentation

### PR DESCRIPTION
**Pull request by kspurgin**
- shows more mappers per page since there are so many when using full manifest
- updates documentation on managing mappers -- splits out into dev and prod environments with prod marked as todo, probably for Mark (?)

### CODE REVIEW

**Comment by mark-cooper** [comment]
@kspurgin is there a specific problem with displaying the digest or do you just not like it? I'd like to include it because it's the easiest & quickest way to confirm that the downloaded mapper is indeed the correct one.

**Comment by kspurgin** [comment]
@mark-cooper Just what I said on the commit message [here.](https://github.com/collectionspace/cspace-batch-import/pull/41/commits/45b1950b8c1b6ce5c40c282ba204a13d2a111957)

Certainly not going to die or even argue on this hill, tho.

**Comment by mark-cooper** [comment]
@kspurgin I think because it's only viewable by admins, and I at least may find it helpful from time to time, lets keep it in.

**Comment by kspurgin** [comment]
@mark-cooper I've reverted the display to once again display the digest

**Pull request merged**
